spring:
 datasource:
  url: jdbc:mysql://mysql-db:3306/images?useSSL=false
  username: root
  password: root
  
 jpa:
  hibernate: 
   ddl-auto: update
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
logging: 
 level:
  org:
   hibernate:
    SQL: debug
    type:
     descriptor:
      sql: trace
