spring:
 datasource:
  url: jdbc:mysql://localhost:3306/MANAS
  username: root
  password: root
 jpa:
  hibernate: 
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
logging: 
 level:
  org:
   hibernate:
    SQL: debug
    type:
     descriptor:
      sql: trace
